services:
 djsd-web:
   image: djsd:latest
   build: .
   network_mode: "host"
   working_dir: /dj_sd
   volumes:
     - /home/ec2-user/dj_sd:/dj_sd
   ports:
     - "80:8000"
   environment:
     ROOT: /dj_sd
