# Generated by Django 5.2 on 2025-06-18 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('number', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=128)),
                ('contact_email', models.CharField(max_length=128)),
                ('contact_phone', models.CharField(max_length=128)),
                ('timezone', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.company'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=128)),
                ('company_account', models.CharField(db_column='company_account', max_length=128, null=True)),
                ('email', models.CharField(db_column='email', max_length=256, null=True)),
                ('phone', models.CharField(db_column='phone', max_length=128, null=True)),
                ('dob', models.DateField(db_column='dob', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subject_line', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=256, null=True)),
                ('sub_category', models.CharField(max_length=256, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_column='number', max_length=128, verbose_name='Policy Number')),
                ('start_date', models.DateField(db_column='start_date', null=True)),
                ('end_date', models.DateField(db_column='end_date', null=True)),
                ('premium_amount', models.DecimalField(db_column='premium_amount', decimal_places=2, max_digits=10, null=True)),
                ('lob', models.CharField(db_column='lob', help_text='Policy business type', max_length=32)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('driving_license', models.CharField(max_length=256)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(db_column='alert_level', max_length=128)),
                ('due_date', models.DateField(db_column='due_date', null=True)),
                ('created_date', models.DateField(db_column='created_date', null=True)),
                ('work_status', models.CharField(db_column='work_status', max_length=128, null=True)),
                ('alert_category', models.CharField(db_column='alert_category', max_length=128, null=True)),
                ('alert_sub_category', models.CharField(db_column='alert_sub_category', max_length=512, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAuthContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('auth_url', models.TextField()),
                ('code', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('policy_alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sd_main.policyalert')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular policy document')),
                ('file_name_uploaded', models.CharField(max_length=512)),
                ('file_name_cloud', models.CharField(max_length=512)),
                ('file_type', models.CharField(max_length=128)),
                ('file_text_extract', models.TextField(null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_to', models.CharField(max_length=256)),
                ('subject_line', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sd_main.customer')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sd_main.policy')),
                ('policy_alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sd_main.policyalert')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sd_main.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('name', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('text_value', models.TextField(default=None, max_length=1024, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_system_setting')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=256)),
                ('license_plate', models.CharField(max_length=256)),
                ('reg_end_date', models.DateField()),
                ('registered_owner', models.CharField(max_length=256)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='AgencySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('text_value', models.TextField(max_length=1024, null=True)),
                ('json_value', models.JSONField(null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agency', 'name'), name='unique_agency_setting')],
            },
        ),
    ]
