# Generated by Django 5.2 on 2025-05-13 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('number', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=128)),
                ('contact_email', models.CharField(max_length=128)),
                ('contact_phone', models.CharField(max_length=128)),
                ('timezone', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.company'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('company_account', models.CharField(max_length=128, null=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=128, null=True)),
                ('dob', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, verbose_name='Policy Number')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('lob', models.CharField(choices=[('Auto', 'Auto'), ('Home', 'Home'), ('Life', 'Life')], default='auto', help_text='Policy business type', max_length=32)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('driving_license', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(max_length=128)),
                ('due_date', models.DateField(null=True)),
                ('created_date', models.DateField(null=True)),
                ('work_status', models.CharField(max_length=128, null=True)),
                ('alert_category', models.CharField(max_length=128, null=True)),
                ('alert_sub_category', models.CharField(max_length=512, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular policy document')),
                ('file_name_uploaded', models.CharField(max_length=512)),
                ('file_name_cloud', models.CharField(max_length=512)),
                ('file_type', models.CharField(max_length=32)),
                ('file_text_extract', models.TextField(null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=50)),
                ('reg_end_date', models.DateField()),
                ('registered_owner', models.CharField(max_length=100)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.policy')),
            ],
        ),
        migrations.CreateModel(
            name='AgencySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('policy_csv_map', 'policy_csv_map'), ('customer_csv_map', 'customer_csv_map'), ('alert_csv_map', 'alert_csv_map')], max_length=100)),
                ('text_value', models.TextField(max_length=1024)),
                ('json_value', models.JSONField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd_main.agency')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agency', 'name'), name='unique_agency_setting')],
            },
        ),
    ]
